### ISSUE TITLE
Chaos Update (v1.0) release checklist 

### ISSUE THREAD

**Issue by AeriaVelocity** [That1M8Head/Sonic-LockandLoad#6]
- [X] Finish all characters' weapon sets
- [x] Finish Sonic's tutorial
- [X] Finish Classic's tutorial
- [x] Finish Shadow's tutorial
- [x] Finish Amy's tutorial
- [x] Iron out any bugs

Feel free to comment suggestions as to what could finish this update up.
**Do not comment suggestions for new content -- I just want to get this thing released**
